App/routes/home.py
#!/usr/local/bin/python
from flask import Blueprint, render_template
import requests
import pandas as pd
import time
import numpy as np
import pickle
import plotly
import plotly.express as px
import json
from lightgbm import LGBMRegressor
# from dotenv import load_dotenv
# import os
# load_dotenv(override=True)

home = Blueprint("home", __name__, static_folder="../static", template_folder="../templates/")

openmodel = open("App/routes/model_rf.pkl", "rb")

model = pickle.load(openmodel)

list_weather1 = ['clear sky', 'few clouds']
list_weather2 = ['mist', 'Smoke', 'Haze', 'Thursday', 'sand/ dust whirls', 'fog', 'light intensity drizzle','drizzle','light intensity drizzle rain',
                    'drizzle rain','shower rain and drizzle','shower drizzle','broken clouds']
list_weather3 = ['light rain', 'moderate rain', 'light snow', 'Snow', '	Sleet','Light shower sleet','Shower sleet','Light rain and snow','Light rain and snow',
                    'Light shower snow', 'Shower snow', 'sand','dust','heavy intensity drizzle','heavy intensity drizzle rain','heavy shower rain and drizzle',
                    'overcast clouds', 'scattered clouds']
list_weather4 = ['thunderstorm with light rain', 'thunderstorm with rain', 'thunderstorm with heavy rain', 'light thunderstorm', 'thunderstorm',
                    'heavy thunderstorm','	ragged thunderstorm','thunderstorm with light drizzle','thunderstorm with drizzle','thunderstorm with heavy drizzle',
                    'heavy intensity rain','very heavy rain','extreme rain','freezing rain','light intensity shower rain','shower rain',
                    'heavy intensity shower rain', 'ragged shower rain', 'Heavy snow', 'Heavy shower snow', 'volcanic ash', 'squalls','tornado']

api_key_holiday= "14ae356bbffb49c58651e72ef87dbf32"
api_key = "1cf4a33bf5ed0e1005a61cb94eded3af"

@home.route('/')
@home.route('/home')
def home_page():
    """[Allow to generate the template of home.html on home path]

    Returns:
        [str]: [home page code]
    """
    
    return render_template('home.html')  

@home.route('/journalier')
def journalier_page():
    """[Allow to generate the template of home.html on home path]

    Returns:
        [str]: [home page code]
    """
    lat = "38.89438"
    lon = "-77.03160"
    url = "https://api.openweathermap.org/data/2.5/onecall?lat=%s&lon=%s&appid=%s&units=metric" % (lat, lon, api_key)
    response = requests.get(url).json()
    prediction = []
    temp_day = 0
    
    
    df_data48h = pd.DataFrame(data=response['hourly'])
    df_data48h = df_data48h.drop(["pressure","dew_point", "uvi", "clouds", "visibility", "wind_deg", "wind_gust", "pop"], axis=1)
    for data48h in response['hourly']:
        date = time.strftime("%D", time.localtime(int(data48h['dt'])))
        hours = time.strftime("%H", time.localtime(int(data48h['dt'])))
        temp = data48h['temp']
        humidity = data48h['humidity']
        windspeed = data48h['wind_speed']
        month = time.strftime("%m", time.localtime(int(data48h['dt'])))
        date = pd.to_datetime(date)
        year = date.year
        weekday = date.weekday()
        day = date.day
        climat = data48h['weather'][0]['description']
        
        if climat in list_weather1:
            weather = 1
        elif climat in list_weather2:
            weather = 2
        elif climat in list_weather3:
            weather = 3
        else:
            weather = 4
            
        if day != temp_day:
            url_holiday = "https://holidays.abstractapi.com/v1/?api_key=%s&country=US&year=%s&month=%s&day=%s" % (api_key_holiday, year, month ,day)
            response_holiday = requests.get(url_holiday).json()
            temp_day = day

        list_working = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
            
        if response_holiday =='':
            holiday = 0
            if weekday in list_working:
                workingday = 1
            else:
                workingday = 0
        else:
            holiday = 1
            workingday = 0
            

        features = [holiday, workingday, weather, temp, humidity, windspeed, month, hours,weekday,year]
        final_features = [np.array(features)]
        df = pd.DataFrame()
        df[['holiday','workingday','weather','temp','humidity','windspeed','month','hours','weekday','year']] = final_features
        df = df.astype({'holiday': 'int64', 'workingday' : 'int64', 'weather': 'int64',
        'temp' : 'float64', 'humidity':'int64', 'windspeed':'float64', 'month':'int64', 'hours':'int64', 'weekday':'int64', 'year':'int64'})

        prediction.append(int(model.predict(df)))
    
    # print(prediction)
    df_data48h['prediction'] = prediction
    heure = []
    date48 = []
    ts = df_data48h['dt']
    for correct_data in ts:
        heure.append(time.strftime("%H:%M", time.localtime(int(correct_data))))
        date48.append(time.strftime("%D", time.localtime(int(correct_data))))
    
    df_data48h['horaire'] = heure
    df_data48h['date48'] = date48
    # print(df)
    fig1 = px.histogram(df_data48h, x ="horaire", y = 'prediction', color="date48", title='prédiction sur les prochaines 48h', barmode="group")
    graph1JSON = json.dumps(fig1, cls=plotly.utils.PlotlyJSONEncoder)
    return render_template('journalier.html', graph1JSON = graph1JSON)  

@home.route('/semaine')
def semaine_page():
    """[Allow to generate the template of home.html on home path]

    Returns:
        [str]: [home page code]
    """
    lat = "38.89438"
    lon = "-77.03160"
    url = "http://api.openweathermap.org/data/2.5/forecast?lat=%s&lon=%s&appid=%s&units=metric" % (lat, lon, api_key)
    response = requests.get(url).json()
    temp_day = 0
    month = []
    date = []
    hours = []
    prediction = []
    temp = []
    humidity = []
    windspeed = []
    heure = []
    date48 = []
    donnee = pd.DataFrame(columns = ['holiday', 'workingday', 'weather', 'temp','humidity', 'windspeed', 'month', 'hours','weekday','year','heure','date48' ]) 
    
    for dataday in response["list"]:
        hours= time.strftime("%H", time.localtime(int(dataday['dt'])))
        month = time.strftime("%m", time.localtime(int(dataday['dt'])))
        date = time.strftime("%D", time.localtime(int(dataday['dt'])))
        temp = dataday['main']['temp']
        humidity = dataday['main']['humidity']
        windspeed =dataday['wind']['speed']
        date = pd.to_datetime(date)
        year = date.year
        weekday = date.weekday()
        heure= time.strftime("%H:%M", time.localtime(int(dataday['dt'])))
        date48= time.strftime("%D", time.localtime(int(dataday['dt'])))
        day = date.day

        climat = dataday['weather'][0]['description']
        # print(climat)
        
        if climat in list_weather1:
            weather = 1
        elif climat in list_weather2:
            weather = 2
        elif climat in list_weather3:
            weather = 3
        else:
            weather = 4
        print(weather)
        if day != temp_day:
            url_holiday = "https://holidays.abstractapi.com/v1/?api_key=%s&country=US&year=%s&month=%s&day=%s" % (api_key_holiday, year, month ,day)
            response_holiday = requests.get(url_holiday).json()
            temp_day = day

        list_working = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
            
        if response_holiday =='':
            holiday = 0
            if weekday in list_working:
                workingday = 1
            else:
                workingday = 0
        else:
            holiday = 1
            workingday = 0
            
        
        to_append = [holiday, workingday, weather, temp,humidity, windspeed, month, hours,weekday,year,heure,date48]
        df_length = len(donnee)
        donnee.loc[df_length] = to_append
            

        features = [holiday, workingday, weather, temp, humidity, windspeed, month, hours,weekday,year]
        final_features = [np.array(features)]
        df = pd.DataFrame()
        df[['holiday','workingday','weather','temp','humidity','windspeed','month','hours','weekday','year']] = final_features
        df = df.astype({'holiday': 'int64', 'workingday' : 'int64', 'weather': 'int64', 
                        'temp' : 'float64', 'humidity':'int64', 'windspeed':'float64', 'month':'int64', 'hours':'int64', 'weekday':'int64', 'year':'int64'})

        prediction.append(int(model.predict(df)))
    

    donnee['prediction'] = prediction
    
    fig1 = px.histogram(donnee, x ="heure", y = 'prediction', color="date48", title='prédiction sur les prochaines 48h', barmode="group")
    graph1JSON = json.dumps(fig1, cls=plotly.utils.PlotlyJSONEncoder)
    
    return render_template('semaine.html', graph1JSON = graph1JSON)

App/routes/info.py
#!/usr/local/bin/python
from calendar import week
import pickle
# from tkinter import X
from flask import Blueprint, request, jsonify
from flask import render_template
from datetime import date, datetime, timedelta
import pandas as pd
import numpy as np
import sklearn
import requests
import json
# from dotenv import load_dotenv
import os
# load_dotenv(override=True)



info = Blueprint("info", __name__, static_folder="../static", template_folder="../templates/")

api_key_holiday= "14ae356bbffb49c58651e72ef87dbf32"
api_key = "1cf4a33bf5ed0e1005a61cb94eded3af"

@info.route('/info', methods=['get', 'post'])
def infos():
    """[Allow to generate the template of home.html on home path]

    Returns:
        [str]: [home page code]
    """

    return render_template('info.html') 

@info.route('/formulaire', methods = ['get', 'post'])
def formulaire():
    api_key_holiday= os.getenv('api_key_holiday')
    hours = request.form['hour']
    date = request.form['date']
    temp = request.form['temp']
    humidity = request.form['humidity']
    windspeed = request.form['windspeed']
    weather = request.form['weather']
    date = pd.to_datetime(date)
    year = date.year
    month = date.month
    weekday = date.weekday()
    date= date.date()
    day = date.day
    
    url_holiday = "https://holidays.abstractapi.com/v1/?api_key=%s&country=US&year=%s&month=%s&day=%s" % (api_key_holiday, year, month ,day)
    response_holiday = requests.get(url_holiday).json()

    list_working = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
        
    if response_holiday =='':
        holiday = 0
        if weekday in list_working:
            workingday = 1
        else:
            workingday = 0
    else:
        holiday = 1
        workingday = 0
        
    data = {'holiday':holiday,'workingday': workingday, 'weather': weather,'temp': temp,'humidity': humidity,'windspeed': windspeed, 'month':month, 'hours': hours,  
              'weekday':weekday, 'year':year}
    
    # x = requests.post('http://127.0.0.1:5001/predict', json=data, headers={'Content-Type': 'application/json'})
    x = requests.post('https://velocapi.herokuapp.com/predict', json=data, headers={'Content-Type': 'application/json'})

    return render_template('date.html', prediction=x.json(), hour=hours, date=date) 

App/templates/base.html
<!doctype html>
<html lang="en">

<head>
  {% block script %}
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

 <title>

  </title>
</head>

<body>




    

  {% block content %}
  {% endblock %}


<script type="text/javascript" src="{{ url_for('static', filename='nuage.js') }}"></script>

  </body>


</html>

App/templates/date.html
{% extends 'base.html' %}

{% block title %}
    Home Page
{% endblock %}


{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<link rel="stylesheet" href="/static/menu.css">
    <button id="toggleDarkMode"></button>
      <div id="ciel"></div>
      <div id="herbe"></div>
      <div id="soleil"></div>
      <div id="nuages"></div>
      <h1 class="text-white">Prévision du nombre de vélo</h1>
      <nav id="cercle1" class="card bg-warning">

        <div id='predict_veloc_hour'>
            <h1>le {{date}} à {{hour}}H il y aura environ {{prediction}} vélos emprunté</h1> 
        </div>
        <div id="main-cercle1">
          <div id="center-circle1">   
              <a href="{{ url_for('info.infos') }}" class="btn btn-primary"><h3>nouvelle date</h3></a>           
          </div>                    
      </div>
    </nav>





    {% endblock %}

App/templates/home.html
{% extends 'base.html' %}

{% block title %}
    Home Page
{% endblock %}

{% block content %}
<link rel="stylesheet" href="/static/menu.css">
<link rel="stylesheet" href="/static/style.css">

<div class="container-fluid">

    <button id="toggleDarkMode"></button>

    <main id="main">
        
      <div id="ciel"></div>
      <div id="herbe"></div>
      <div id="soleil"></div>
      <div id="nuages"></div>
      <h1 class="text-white">Prévision du nombre de vélo</h1>
      <nav id="cercle">
        <div id="main-cercle">
            <div id="center-circle">
                <ul>
                    <li class="ch-img-1 ch-item">
                      <div class="ch-info">
                        <a href="{{ url_for('home.semaine_page') }}"><h3>Prévision vélo sur 5 jours</h3></a>
                      </div>
                    </li>
                    <li class="ch-img-2  ch-item">
                      <div class="ch-info">
                        <a href="{{ url_for('home.journalier_page') }}"><h3>Prévision vélo sur la journée</h3></a>
                      </div>
                    </li>
                    <li class="ch-img-3  ch-item">
                      <div class="ch-info">
                        <a href="{{ url_for('info.infos') }}"><h3>Prévision vélo selon la date et l'heure</h3></a>
                      </div>
                    </li>
                </ul>                
            </div>                    
        </div>
    </nav>
    </main>

</div>

{% endblock %}

App/templates/info.html
{% extends "base.html" %}
{% block title %}
  Saisie comme tu veux
{% endblock %}

{% block content%}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="/static/menu.css">
  <div id="ciel"></div>
  <div id="herbe"></div>
  <div id="soleil"></div>
  <div id="nuages"></div>
<div class='container mt-5 card bg-light'>

  <img src="https://www.gov.je/_controltemplates/15/C5.MetOfficeResponsive/images/icons/b.svg" width="100">
    <form  action = "{{url_for('info.formulaire')}}" method="post" >

        <div class="form-group">
          <label for= "date">Enter date: </label>
          <input type="date" class="form-control" name = 'date' id= 'date'>
        </div>

        <div class="form-group">
          <label>Enter hour: </label>
          <input type="appt-time" name="hour" class="form-control" id="hour" placeholder="18">
        </div>

        <div class="form-group">
            <label>Enter temperature (in °C): </label>
            <input type="appt-time" name = 'temp' class="form-control" id="exampleInputPassword1" placeholder="20">
          </div>

          <div class="form-group">
            <label>Enter humidity (in %): </label>
            <input type="appt-time" name = 'humidity' class="form-control" id="exampleInputPassword1" placeholder="14">
          </div>

          <div class="form-group">
            <label>Enter windspeed (in km/h): </label>
            <input type="appt-time" name= 'windspeed' class="form-control" id="exampleInputPassword1" placeholder="20">
          </div>

          <div class="form-group">
            <label>Enter type of weather: </label>
            <select name='weather' class="form-control" id="weather" >
            <option value=1>Clear/ Few clouds/ Partly cloudy</option>
            <option value=2>Mist + Cloudy/ Mist + Broken clouds/ Mist + Few clouds/ Mist</option>
            <option value=3>Light Snow/ Light Rain + Thunderstorm + Scattered clouds/ Light Rain + Scattered clouds</option>
            <option value=4> Heavy Rain + Ice Pallets + Thunderstorm + Mist/ Snow + Fog </option>
            </select>
          </div>



        
        
        <button type="submit" class="btn btn-danger mb-3">Predict Rentals</button>
      </form>
</div>
{% endblock %}

App/templates/journalier.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid" id="chart1">
  
</div>

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

<script type="text/javascript">
  var graphs1 = {{ graph1JSON | safe}};
  Plotly.plot("chart1", graphs1,{});
</script>

{% endblock %}

App/templates/result_pred.html
{% extends 'base.html' %}

{% block title %}
    Home Page
{% endblock %}

{% block content %}



    <button id="toggleDarkMode"></button>

    
        
      <div id="ciel"></div>
      <div id="herbe"></div>
      <div id="soleil"></div>
      <div id="nuages"></div>
      <h1 class="text-white">Prévision du nombre de vélo</h1>
      <nav id="cercle1">
        <div id="main-cercle1">
            <div id="center-circle1">   
                <a href="{{ url_for('info.infos') }}"><h3>nouvelle date</h3></a>           
            </div>                    
        </div>
        <div id='predict_veloc_hour'>
            <h1>le {{date}} il y aura environ {{prediction}} vélos emprunté</h1> 
        </div>

    </nav>





    {% endblock %}

App/templates/semaine.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid" id="chart1">
  
</div>

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

<script type="text/javascript">
  var graphs1 = {{ graph1JSON | safe}};
  Plotly.plot("chart1", graphs1,{});
</script>

{% endblock %}